import { AllocationUpdatedEventObject, NitroAdjudicator } from './adjudicator/nitro-adjudicator';
import { Address } from '../../../types/types';

// getChainHolding reads on-chain holdings for a channel and an asset address given a transaction and an event generated by the transaction.
// TODO: Implement
export function getChainHolding(na: NitroAdjudicator, tx: any, event: AllocationUpdatedEventObject): [Address, bigint] {
  return ['', BigInt(0)];
}
