name: "Lint and Test"

on:
  pull_request:
    branches: "*"
  push:
    branches: "main"

jobs:
  lint:
    name: "Run lint"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install dependencies"
        run: yarn
      - name: "Linter check"
        run: yarn lint
  test-browser:
    name: "Run tests for browser"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install dependencies"
        run: yarn
      - name: "Run tests"
        run: |
          yarn build:browser --ignore @cerc-io/example-web-app
          yarn test:browser
  test-node:
    name: "Run tests for node"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install dependencies"
        run: yarn
      - name: "Run tests"
        run: |
          yarn build:node
          yarn test:node
